### ISSUE TITLE
BertClient can't work without bert-serving-server

### ISSUE THREAD

**Issue by yesxiaoyu** [rameshjesswani/NLP-#2]
Thanks for shared this notebook, but the question occured when using BertClient is bert-serving-start?

**Comment by rameshjesswani** [comment]
Yes, you have to start server by following guidelines here: [bert-as-service](https://github.com/hanxiao/bert-as-service)
Sorry for late reply.

**Comment by nstfk** [comment]
Hi,
Can we run both server and client in google colab hotsed runtime?

**Comment by rameshjesswani** [comment]
@nstfk I never tried that, but to me this seems possible.

**Comment by rameshjesswani** [comment]
I hope problem is resolved. so i will close this issue. Feel free to re-open if you have any issues.
