### ISSUE TITLE
I am trying to run through the notebook getting error

### ISSUE THREAD

**Issue by sandeeppilania** [rameshjesswani/NLP-#3]
`WARNING:tensorflow:From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
claims (InputLayer)          (None, 138, 768)          0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 16)                50240     
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 136       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
=================================================================
Total params: 50,385
Trainable params: 50,385
Non-trainable params: 0
_________________________________________________________________
None
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-b0f7103a87fc> in <module>()
     75 history = model.fit({'claims': claims_vec}, labels, 
     76                             epochs=5, batch_size=32, validation_split=0.1, callbacks=[early_stopping, metrics,
---> 77                                             ModelCheckpoint(filepath='model_imdb_lstm_bert.h5', monitor='val_loss', save_best_only=True)])

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
    950             sample_weight=sample_weight,
    951             class_weight=class_weight,
--> 952             batch_size=batch_size)
    953         # Prepare validation data.
    954         do_validation = False

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)
    749             feed_input_shapes,
    750             check_batch_axis=False,  # Don't enforce the batch size.
--> 751             exception_prefix='input')
    752 
    753         if y is not None:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    126                         ': expected ' + names[i] + ' to have ' +
    127                         str(len(shape)) + ' dimensions, but got array '
--> 128                         'with shape ' + str(data_shape))
    129                 if not check_batch_axis:
    130                     data_shape = data_shape[1:]

ValueError: Error when checking input: expected claims to have 3 dimensions, but got array with shape `

**Comment by rameshjesswani** [comment]
sorry, what file you are trying to run?

**Comment by sandeeppilania** [comment]
bert_imdb_lstm.ipynb

**Comment by sandeeppilania** [comment]
also can you tell me why you are using max_claims_length = 138
max_sents_length = 138 . why 138 ? i am not able to figure it out

**Comment by rameshjesswani** [comment]
it is just chosen randomly, you can change it also according to the max length in your dataset.

**Comment by sandeeppilania** [comment]
Thanks for replying,
I am pretty new to BERT and deep learning.
I am trying to some text classification using BERT embeddings and somehow i am just stuck with it. And thats where i was trying to mimic your solution.

So, i have a claims_vec (which just word embeddings of shape[80345,768] and have labels in a vec as well.  So, help me this :

what would be the values of parameters for me while calling this:
and i have 7 classes.
claims_input, pred_label = training.lstm_model(max_claims_length = ? , embedding_dim = 768, nb_classes = 7)

**Comment by rameshjesswani** [comment]
If you are new to deep learning, then you should start from word2vec/glove embeddings and construct LSTM model. There is no point of directly jumping to advanced approaches if you don't know the basic ones. I would suggest you to check book ```Deep learning with keras by francois chollet```
